[package]
name = "tiny-secp256k1-wasm"
version = "0.1.0"
authors = ["junderw <junderwood@bitcoinbank.co.jp>", "yuki-js <20838151+yuki-js@users.noreply.github.com>"]
edition = "2018"
license = "MIT"
repository = "https://github.com/junderw/tiny-secp256k1-wasm"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.63"
